Daedra = {
    Summoned = {
        atronach_flame_summon      = true,
        atronach_frost_summon      = true,
        atronach_storm_summon      = true,
        clannfear_summon           = true,
        dremora_summon             = true,
        ["golden saint_summon"]    = true,
        hunger_summon              = true,
        scamp_summon               = true,
        ["winged twilight_summon"] = true,
    },
    Normal = {
        -- vanilla
        atronach_flame              = true,
        atronach_flame_az           = true,
        atronach_flame_ttmk         = true,
        atronach_frost              = true,
        atronach_frost_ttmk         = true,
        atronach_frost_gwai_uni     = true,
        atronach_storm              = true,
        atronach_storm_az           = true,
        atronach_storm_ttmk         = true,
        clannfear                   = true,
        daedroth                    = true,
        daedroth_az                 = true,
        daedroth_baladas            = true,
        daedroth_fg_nchur           = true,
        daedroth_menta_unique       = true,
        dremora_ttmg                = true,
        dremora                     = true,
        dremora_gothren_guard1      = true,
        dremora_gothren_guard2      = true,
        dremora_ttpc                = true,
        dremora_lord                = true,
        dremora_special_Fyr         = true,
        ["golden saint"]            = true,
        ["golden saint_staada"]     = true,
        hunger                      = true,
        hunger_audenian             = true,
        hunger_az_01                = true,
        hunger_az_02                = true,
        hunger_fghl                 = true,
        ogrim                       = true,
        ogrim_az                    = true,
        ["ogrim titan"]             = true,
        scamp                       = true,
        lustidrike                  = true,
        scamp_mg_apprentice         = true,
        scamp_creeper               = true,
        ["winged twilight"]         = true,
        ["winged twilight_grunda_"] = true,
        -- Tamriel Data
        T_Dae_Cre_MonarchFr_01      = true,
        T_Dae_Cre_MonarchSt_01      = true,
        T_Dae_Cre_Auroran_01        = true,
        T_Dae_Cre_Auroran_02        = true,
        T_Dae_Cre_LesserClfr_01     = true,
        T_Dae_Cre_Drem_Arch_01      = true,
        T_Dae_Cre_Drem_Cast_01      = true,
        T_Dae_Cre_DremCait_01       = true,
        T_Dae_Cre_DremKynv_01       = true,
        T_Dae_Cre_DremKynr_01       = true,
        T_Dae_Cre_DremCyr_01        = true,
        T_Dae_Cre_DremLorCyr_01     = true,
        T_Dae_Cre_GSaintCyr_01      = true,
        T_Dae_Cre_Herne_01          = true,
        T_Dae_Cre_Devourer_01       = true,
        T_Dae_Cre_Guardian_01       = true,
        T_Dae_Cre_Morphoid_01       = true,
        T_Dae_Cre_Perthan_01        = true,
        T_Dae_Cre_Seduc_01          = true,
        T_Dae_Cre_SeducDark_01      = true,
        T_Dae_Cre_SeducDark_02      = true,
        T_Dae_Cre_SeducDark_t2      = true,
        T_Dae_Cre_SpiderDae_01      = true,
        T_Dae_Cre_Verm_01           = true,
        T_Dae_Cre_Xivilai_01        = true,
        -- OAAB_Data

        -- The Doors of Oblivion
        
    }
}
